# Generated by Django 2.2.5 on 2019-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
