version: "2"

services:
  backend:
    container_name: atria_backend
    build: ./atria_backend
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && pip install -r requirements.txt
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./atria_backend:/code
    ports:
      - "8000:8000"
  frontend:
    container_name: atria_frontend
    build: ./atria_frontend
    volumes:
      - "./atria_frontend:/usr/src"
      - "/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
